Use uri.netloc() instead of uri.host when sending HTTP requests
smithy-lang/smithy-python pull request #187
Opened 2023-11-17 12:20 UTC by gscalise

When `send`ing a request using `AIOHTTPClient` the endpoint URI is split into URL and query string. The URL resulting from calling `_serialize_uri_without_query` is missing parts of the URI (user, password and port), which causes issues when using non-standard ports.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2023-11-20 13:36 UTC, JordonPhillips requested changes

2023-11-20 13:36 UTC, JordonPhillips commented on python-packages/smithy-python/smithy_python/_private/http/aiohttp_client.py
> +        components = (uri.scheme, uri.netloc(), uri.path or "", "", "", "")
```suggestion
        components = (uri.scheme, uri.netloc, uri.path or "", "", "", "")
```

2023-11-21 10:14 UTC, gscalise commented on python-packages/smithy-python/smithy_python/_private/http/aiohttp_client.py
> +        components = (uri.scheme, uri.netloc(), uri.path or "", "", "", "")
Done!

2023-11-21 10:24 UTC, JordonPhillips approved these changes

2023-11-21 10:25 UTC, merged