Add fault attribute to generated errors
smithy-lang/smithy-python pull request #190
Opened 2023-11-29 00:19 UTC by haydenbaker

*Description of changes:*
- Generated service errors (modeled with `@error`) should have the [fault (client or server)](https://smithy.io/2.0/spec/type-refinement-traits.html#error-trait) as an attribute

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2023-12-05 14:07 UTC, JordonPhillips requested changes
This needs to be in one of the base classes/ interfaces so that it can be seen generically by things like retry handlers.

2024-01-03 15:14 UTC, JordonPhillips approved these changes, later dismissed
Actually, we should be able to use protocols instead and it'll be fine. I've updated the PR to add fault to the unknown api error and make use of more code blocks.

2024-01-26 16:40 UTC, haydenbaker commented on python-default.lock
Whenever dependencies change, we need to make sure we upgrade and commit the lock-file. 
```
./pants generate-lockfiles
```

2024-03-05 16:44 UTC, JordonPhillips approved these changes

2024-03-05 16:48 UTC, merged