Event stream signature
smithy-lang/smithy-python pull request #318
Opened 2024-10-17 13:06 UTC by JordonPhillips

This adds in the interfaces for event streams and updates code generation to use them.

Example generated operation:

```python
async def stream_messages(
    self,
    input: StreamMessagesInput,
    plugins: list[Plugin] | None = None,
) -> EventStream[
    InputEventStream[MessageStream],
    OutputEventStream[MessageStream],
    StreamMessagesOutput,
]:
    raise NotImplementedError()
```

These were part of separate prs that included http context, which has been removed. Doc strings have also been majorly beefed up. Example useage from the beefed up docs:

```python
async def main():
    client = ChatClient()
    input = StreamMessagesInput(chat_room="aws-python-sdk", username="hunter7")

    async with client.stream_messages(input=input) as stream:
        stream.input_stream.send(MessageStreamMessage("Chat logger starting up."))
        response_handler = handle_output(stream)
        stream.input_stream.send(MessageStreamMessage("Chat logger active."))
        await response_handler

    async def handle_output(stream: EventStream) -> None:
        _, output_stream = await stream.await_output()
        async for event in output_stream:
            match event:
                case MessageStreamMessage():
                    print(event.value)
                case MessageStreamShutdown():
                    return
                case _:
                    stream.input_stream.send(
                        MessageStreamMessage("Unknown message type received. Shutting down.")
                    )
                    return
```

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2024-10-17 13:39 UTC, JordonPhillips commented
I also had to add suppressions for new protocol tests that assert http-binding behaviors. We'll be re-writing all that binding code soon, so there's little value in fixing it now.

2024-10-18 13:59 UTC, JordonPhillips commented
I split the suppressions out into another pr since it was blocking everything

2024-10-18 16:04 UTC, nateprewitt requested changes
Couple typos, otherwise looks good.

2024-10-18 16:04 UTC, nateprewitt commented on python-packages/smithy-event-stream/smithy_event_stream/aio/interfaces.py
> +        receive events, which may be before the intitial response has been received
```suggestion
        receive events, which may be before the initial response has been received
```

2024-10-18 17:10 UTC, JordonPhillips commented
No idea why codecov ate it

2024-10-18 19:43 UTC, nateprewitt approved these changes
Looks like a transient 503 for CodeCov, succeeded on retry.

2024-10-18 20:42 UTC, merged